import type {
  CallLog,
  CrewMember,
  Estimate,
  Expense,
  Job,
  ShopMessage,
  TimeCard,
} from "./types";
import { weekdayHours } from "./schedule";

const thisMorning = "2026-09-10T11:29:00.000Z";
const danaStart = "2026-09-10T10:15:00.000Z";
const livStart = "2026-09-10T12:20:00.000Z";

export const CREW: CrewMember[] = [
  {
    id: "e-mike",
    name: "Mike Reyes",
    role: "HVAC Lead",
    phone: "(206) 555-0130",
    photoUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    status: "active",
    currentJob: "Unit 4B — HVAC replacement",
    currentJobId: "c-northline",
    startedAt: thisMorning,
    weeklyHoursTarget: 40,
    weeklyHoursLogged: 4.5,
    weeklySchedule: weekdayHours("07:00", "16:00"),
    lat: 47.62482,
    lng: -122.3629,
    gpsLive: true,
    battery: 74,
    speedMph: 22,
    lastCheckIn: thisMorning,
    inviteToken: "jc_mike_reyes",
  },
  {
    id: "e-dana",
    name: "Dana Cole",
    role: "Electrician",
    phone: "(206) 555-0176",
    photoUrl: "https://randomuser.me/api/portraits/women/65.jpg",
    status: "active",
    currentJob: "Cedar fence + gate · Capitol Hill",
    currentJobId: "c-hale",
    startedAt: danaStart,
    weeklyHoursTarget: 36,
    weeklyHoursLogged: 8,
    weeklySchedule: weekdayHours("08:00", "16:00", ["mon", "tue", "wed", "thu"]),
    lat: 47.62572,
    lng: -122.3089,
    gpsLive: true,
    battery: 88,
    speedMph: 11,
    lastCheckIn: danaStart,
    inviteToken: "jc_dana_cole",
  },
  {
    id: "e-sam",
    name: "Sam Park",
    role: "Plumber",
    phone: "(206) 555-0181",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "off",
    currentJob: "On call",
    currentJobId: null,
    startedAt: null,
    weeklyHoursTarget: 20,
    weeklyHoursLogged: 0,
    weeklySchedule: weekdayHours("08:00", "12:00", ["mon", "wed", "fri"]),
    lat: null,
    lng: null,
    gpsLive: false,
    battery: 41,
    speedMph: 0,
    lastCheckIn: null,
    inviteToken: "jc_sam_park",
  },
  {
    id: "e-liv",
    name: "Liv Turner",
    role: "Apprentice",
    phone: "(206) 555-0144",
    photoUrl: "https://randomuser.me/api/portraits/women/21.jpg",
    status: "break",
    currentJob: "Unit 4B — HVAC replacement",
    currentJobId: "c-northline",
    startedAt: livStart,
    weeklyHoursTarget: 40,
    weeklyHoursLogged: 3.5,
    weeklySchedule: weekdayHours("07:30", "16:30"),
    lat: 47.62435,
    lng: -122.3641,
    gpsLive: true,
    battery: 19,
    speedMph: 4,
    lastCheckIn: livStart,
    inviteToken: "jc_liv_turner",
  },
];

export const JOBS: Job[] = [
  {
    id: "c-vasquez",
    customerName: "Elena Vasquez",
    phone: "(206) 555-0147",
    address: "2418 9th Ave W, Seattle, WA 98119",
    jobTitle: "Exterior paint · Queen Anne",
    status: "in_progress",
    scheduledTime: "08:30 AM",
    worker: "Unassigned",
    workerId: null,
    priority: "high",
    lat: 47.639844278404,
    lng: -122.368877694281,
  },
  {
    id: "c-hale",
    customerName: "Jordan Hale",
    phone: "(206) 555-0192",
    address: "732 18th Ave E, Seattle, WA 98112",
    jobTitle: "Cedar fence + gate · Capitol Hill",
    status: "in_progress",
    scheduledTime: "07:45 AM",
    worker: "Dana Cole",
    workerId: "e-dana",
    priority: "medium",
    lat: 47.625540435866,
    lng: -122.308577423016,
  },
  {
    id: "c-northline",
    customerName: "Northline Properties",
    phone: "(206) 555-0110",
    address: "1847 W Mercer St, Seattle, WA 98119",
    jobTitle: "Unit 4B — HVAC replacement",
    status: "in_progress",
    scheduledTime: "08:30 AM",
    worker: "Mike Reyes",
    workerId: "e-mike",
    priority: "high",
    lat: 47.6246084,
    lng: -122.3635414,
  },
  {
    id: "c-shah",
    customerName: "Priya Shah",
    phone: "(206) 555-0164",
    address: "1610 15th Ave, Seattle, WA 98122",
    jobTitle: "Interior paint · living + hall",
    status: "lead",
    scheduledTime: "10:00 AM",
    worker: "Unassigned",
    workerId: null,
    priority: "low",
    lat: 47.615450303025,
    lng: -122.312680476486,
  },
  {
    id: "c-chen",
    customerName: "Maya Chen",
    phone: "(206) 555-0128",
    address: "1421 NW 61st St, Seattle, WA 98107",
    jobTitle: "Deck stain · Ballard",
    status: "scheduled",
    scheduledTime: "01:30 PM",
    worker: "Unassigned",
    workerId: null,
    priority: "medium",
    lat: 47.6729,
    lng: -122.376,
  },
  {
    id: "c-elliott",
    customerName: "Elliott Bay Tower",
    phone: "(206) 555-0188",
    address: "400 Broad St, Seattle, WA 98109",
    jobTitle: "Rooftop unit swap",
    status: "completed",
    scheduledTime: "Yesterday",
    worker: "Mike Reyes",
    workerId: "e-mike",
    priority: "high",
    lat: 47.61982222018,
    lng: -122.348868893303,
    signature: null,
  },
  {
    id: "c-owens",
    customerName: "Pat Owens",
    phone: "(501) 385-0160",
    address: "112 Ridgeway St, Hot Springs, AR 71901",
    jobTitle: "Cabinets + trim · downtown",
    status: "dispatched",
    scheduledTime: "02:00 PM",
    worker: "Sam Park",
    workerId: "e-sam",
    priority: "medium",
    lat: 34.5037,
    lng: -93.0552,
  },
  {
    id: "c-lakeside",
    customerName: "Lakeside HOA",
    phone: "(501) 385-0220",
    address: "8 Lake Shore Dr, Hot Springs, AR 71913",
    jobTitle: "Clubhouse exterior",
    status: "invoiced",
    scheduledTime: "Last Friday",
    worker: "Dana Cole",
    workerId: "e-dana",
    priority: "high",
    lat: 34.451,
    lng: -93.081,
  },
];

export const ACTIVE_JOBS = JOBS.filter((job) => job.status === "in_progress");

export const ESTIMATES: Estimate[] = [
  {
    id: "est-hale",
    jobId: "c-hale",
    amount: 5327.7,
    notes: "Cedar fence and gate package",
    createdAt: "2026-09-09T18:00:00.000Z",
    labor: 2800,
    materials: 1400,
    markup: 0.18,
    taxRate: 0.075,
  },
];

export const TIMECARDS: TimeCard[] = [
  {
    id: "tc-mike-1",
    employeeId: "e-mike",
    jobId: "c-northline",
    hours: 4.5,
    date: "2026-09-10",
    notes: "HVAC demo and recovery",
  },
  {
    id: "tc-dana-1",
    employeeId: "e-dana",
    jobId: "c-hale",
    hours: 8,
    date: "2026-09-10",
    notes: "Fence layout and posts",
  },
];

export const EXPENSES: Expense[] = [
  {
    id: "exp-sherwin",
    employeeId: "e-mike",
    jobId: "c-northline",
    vendor: "Sherwin-Williams",
    amount: 187.44,
    category: "Materials",
    photoUrl: null,
    createdAt: "2026-09-10T16:10:00.000Z",
  },
  {
    id: "exp-fuel",
    employeeId: "e-dana",
    jobId: "c-hale",
    vendor: "Pilot",
    amount: 64.2,
    category: "Fuel",
    photoUrl: null,
    createdAt: "2026-09-10T12:40:00.000Z",
  },
];

export const CALLS: CallLog[] = [
  {
    id: "call-rosa",
    callerName: "Rosa Bennett",
    phone: "(501) 385-0194",
    transcript:
      "Hi, this is Rosa on Central. Can Top Gun come quote the south wall and fascia this week?",
    summary: "Wants an exterior paint quote on Central Avenue.",
    intent: "Estimate",
    createdAt: "2026-09-11T14:22:00.000Z",
    convertedJobId: null,
  },
];

export const MESSAGES: ShopMessage[] = [
  {
    id: "msg-weather",
    fromId: "e-mike",
    body: "Storm cell after 3. Wrap exteriors by 2:30.",
    createdAt: "2026-09-11T13:05:00.000Z",
    broadcast: true,
  },
];
